# -*- coding: utf-8 -*-
"""loop for in range.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bUorEnDdRZNgO0sVTr2O6wiD8ay-GVDv
"""

# Disciplina: Probabilidade e Estatística
# Aluno: gabriel rodrigues da silva
# Lista 4


x=input ('Digite um número inteiro:') #pega o numero
x=int(x) #garante que e inteiro
for x in range(0,x + 1): #laço pra mostrar a sequencia
    print(x)