# -*- coding: utf-8 -*-
"""manipulação de string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d7LvtFPrJYqlnjQghZ2IACdDghLNJP8K
"""

# Disciplina: Probabilidade e Estatística
# Aluno: gabriel rodrigues da silva
# Lista 4

x=int(input('Informe um número entre 1000 e 9999: '))# pego numero
u=str(x) #transformação em string
print('O número informado foi:',x)#mostra o numero digitado
print('Unidade: {}' '\nDezena: {}' '\nCentena: {}' '\nMilhar: {}'.format(u[3], u[2], u[1], u[0]))#mostra no formato pedido separando